language: python
python: "3.6"
services:
  -postgresql
env:
  -DJANGO_SETTINGS_MODULE=pingit_clone.settings.testing
before-install:
  - sudo apt-get update
install:
  - pip install -r requirements/development.txt
script:
  - cd pingit_clone/
  - pytest
