branches:
  only:
  - master
language: python
python: '3.6'
services: "-postgresql"
before_install:
- openssl aes-256-cbc -K $encrypted_8fb3ffa45001_key -iv $encrypted_8fb3ffa45001_iv
  -in .travis/push_certificate.pem.enc -out .travis/push_certificate.pem -d
- sudo apt-get update
install:
- pip install -r requirements/development.txt
before_script:
- psql -c 'create database travis_ci_test_db;' -U postgres
script:
- export DJANGO_SETTINGS_MODULE=pingit_clone.settings.testing
- cd pingit_clone/
- python manage.py makemigrations banking
- python manage.py makemigrations customers
- python manage.py migrate banking
- python manage.py migrate customers
- pytest
after_success:
- eval "$(ssh-agent -s)"
- cd ../
- chmod 600 .travis/push_certificate.pem
- ssh-add .travis/push_certificate.pem
- git remote add deploy pingit@172.104.61.45:/webapps/repo/pingit_clone
- git status
- git branch
- git log
