language: python
python: '3.6'
services: "-postgresql"
env:
  global:
  - secure: whxAkpW21YPTmR8aTSaePwTvrJpozwmjbNFZNhQrR73m9tm+2eB+rCVXBSRudpN96q04h9hr8cL1Ku8huqGZbKZTSrWfFbxpQ6N3Lq6Vh4jaqh64Hoog8W+2R0D7HGc2+OpHE1GvB6OBhD+/lQLSxgP4n/RVOPd0MMxHwXOQsSqS1iTzrkHYCbpfKb60mUPVIDSoyTtsD8gZQQAv818LlVASaDMQHOp94qlP37TB5pZU1VSO3nsZ+ttBx4ykHTQ+lfvQqh6PzKdducugLp2MYmFdF5des8VAmbEGf3lEh/gv7LYxj4HcwOhHmecRrGP4wuVatyBvdx6G8SJK+MYz4ZbzUmbKw+VH14uwmuGY08KyWkeVNLvYUDCphac8CUiSAfi2EMIQppynqysKmSCHojvuSzkIjNcAj1egudpKEXxF4t8J9tZH5RSA4OA9fdbS1M022FIHXpkCILQ1Y9AFENWNspW/30mhluJuROUyWwLqNXE62b1fB3jUANA6PRMZ6eukJG5v8tJA8l6sOgvJGpceC4+rGqs8y7bPxNhk/4hW7dWqoqTteqAeqikFoNc4jHN2dv23wE86gcAXxTrCJNFLJ+B/HA+xZT/gX2HX7G+DF+LJps5Ob6hDyA4WMTnM9jtpSNJPBqC1Esaj9V1IFA1BlDB/OrLJCHhcCqWIyUc=
before-install:
- sudo apt-get update
install:
- pip install -r requirements/development.txt
before_script:
- psql -c 'create database travis_ci_test_db;' -U postgres
script:
- export DJANGO_SETTINGS_MODULE=pingit_clone.settings.testing
- cd pingit_clone/
- python manage.py makemigrations banking
- python manage.py makemigrations customers
- python manage.py migrate banking
- python manage.py migrate customers
- pytest
