language: python
python: '3.6'
services: "-postgresql"
before-install:
- sudo apt-get update
install:
- pip install -r requirements/development.txt
before_script:
- psql -c 'create database travis_ci_test_db;' -U postgres
script:
- export DJANGO_SETTINGS_MODULE=pingit_clone.settings.testing
- export SECRET_KEY="t@+pp-jo4e2^+hsb(vb+*1s^=@lsg$t7pgr(&^&fe4#_y@s%m9"
- cd pingit_clone/
- python manage.py makemigrations
- python manage.py migrate
- pytest
