language: python
python: '3.6'
services: "-postgresql"
env:
  global:
  - secure: sLc6az4y4MJbQWzZJQrhuqPt6uYOtr5Tyd4OzUmRgZIvCw13LrCmv+iH6R9hxXBXv34Yd0nj2Hk5KKpWNn+kp5gCAkDT9VxDrCn/LllU6fh0lt4YC4x0/p1cnm7Dyg9R0kP5/en6uiHmTwonJP6/EFAghJrSOznOSiRy7kJXnpUT0DKh0qdnB5VN2zB8XimQZIiC1k1jLkM/K4vwp5j8oBkB035J8VNCa5UnT9bE+z/0umQRAj57x7irs7FQ3mSw7UzoA/hKH2sDLxKI+NfkqW99Hr0eixn6mFEXxEZaPWYkxDzKgh2/jOBMNUlVcB+oz4U5uVtkMHG7sAc/jdcTwonTBifLMMWL1SFs/loTS4BqDt83xyuyfKwPwvIGqMl1pWrDJlNE3VjbnWMxfTO940/cAOIRk659ipbSeYldNjT4NIGwRigKNV2y04rQokqF0PB026rCu8ogOe5Wt2On7JHjfkZOVbixcJG5VXUQMVvuDn7D/kVu+hd4ba1E6ksQXyDRE+lPTrOErKBmk09d3xE8ZDkf8KJJ7S+lGH4odsC+3jRVLnSgtNYaFL4wGkBg8GgltZeKRsiH4ZQfuMedC6uqgBJaUufzvmOVTHvBHaFVGhBp9ejv95a4FNcmlZFs65CuJ24n9IM4IqEzuivjNVxk4M7jR0idrk7hucDHx20=
before-install:
- sudo apt-get update
install:
- pip install -r requirements/development.txt
before_script:
- psql -c 'create database travis_ci_test_db;' -U postgres
script:
- export DJANGO_SETTINGS_MODULE=pingit_clone.settings.testing
- cd pingit_clone/
- python manage.py makemigrations banking
- python manage.py makemigrations customers
- python manage.py migrate banking
- python manage.py migrate customers
- pytest
