# Generated by Django 2.1.2 on 2018-10-08 06:06

import customers.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', customers.managers.CustomerManager()),
            ],
        ),
    ]
