# Generated by Django 2.1.2 on 2018-10-07 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('current_balance', models.FloatField(default=0.0)),
                ('other_details', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_ID', models.CharField(max_length=3)),
                ('merchant_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_amount', models.FloatField(default=0.0)),
                ('other_details', models.CharField(max_length=140)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.Account')),
                ('merchant_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.Merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.TransactionType'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_status_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.AccountStatus'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.AccountType'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
