# Generated by Django 2.1.2 on 2018-10-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20181008_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_ID',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
