# Generated by Django 2.1.2 on 2018-10-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20181010_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created']},
        ),
    ]
