# Generated by Django 2.1.2 on 2018-10-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_auto_20181010_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created']},
        ),
    ]
