# Generated by Django 2.1.2 on 2018-10-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_auto_20181011_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
    ]
